### ISSUE TITLE
Super Sound Muffler Revised

### ISSUE THREAD

**Issue by Iceciro** [SoSly/minecraft#21]
**Mod URL:**  https://www.curseforge.com/minecraft/mc-mods/super-sound-muffler-revived

**Mod Description:** Super Sound Muffler is a simple mod that helps to muffle annoying sounds in the game. i.e chickens. Unlike other sound mufflers, which mute all sounds in an area, Super Sound Muffler allows you to specify which sounds you want to muffle.

**Why you want it:** Lots of things are loud and annoying. Phoenixes (most of Extra Birds, really), sheep, Gourmallylis, etc. Sometimes those things are near my house. Sometimes I like to hear myself think.

**Comment by nivthefox** [comment]
I have some concerns about how this will affect stability.  It has the potential to be very laggy.  That said, I think in concept this is really cool, so we'll test it out as a 4.1 mod.
