### ISSUE TITLE
Astral Sorcery Configuration Changes

### ISSUE THREAD

**Issue by InterwovenWasTaken** [SoSly/minecraft#31]
Config alterations for Astral Sorcery
Remove random plant mutation so that wearing the Aevitas cape can be worn without damaging farms/parks by using the following:

        # Defines the chance that the aoe will search for a plant to turn into another plant. [range: 0.0 ~ 1.0, default: 0.2]
        S:aevitasPlantTransformChance=0.0

Remove block-destroying explosions from random shooting stars by using the following:

        # Set to true to make shooting stars do a little explosion where they land [default: true]
        B:doExplosion=false

**Comment by nivthefox** [comment]
I kinda like the shooting star explosions. Are they problematic?

Also, can you explain the Aevitas thing to me a bit more?

**Comment by InterwovenWasTaken** [comment]
The shooting star explosions leave holes in the landscape like TNT or creepers, and cannot be directed - they just fall 'near a player'. And they've required cleanup already, though they haven't impacted a building yet to my knowledge. Were one to impact Rob's church with the current settings, a lot of effort and difficult-to-replace Dark Prismarine would be destroyed.

To be clear, Shooting Stars would still spawn, and still land, they just wouldn't destroy blocks.

So the Aevitas Mantle of Stars has four weak effects instead of one strong one.
1) It very slowly regenerates your health (It adds a little to natural healing.)
2) It very slowly regenerates your hunger, though it won't give meaningful satiation (you have to stand very, very still to get even one satiation ham, and it takes time.)
3 and 4) In a radius around you, it checks for plants and does one of three things: Usually, nothing. Rarely, it changes the plant into another plant - a pumpkin or melon, generally, as far as I've seen. Rarely, it applies a bonemeal effect.

This config option would cause it to retain the slow health regen, slow hunger regen, and rare bonemeal, but it would no longer replace plants with other plants. That would make it non-risky for me to give druids an aura of plant growth, or to visit the various farms while I'm using it to fill my hearts after they've been emptied by logging in. (That's a known bug and I'm not aware of a graceful solution; I just heal them up so it's been fine.)

**Comment by nivthefox** [comment]
**Can** falling stars damage non-soft blocks? I know at least with Dragonfire we've got it set to only do soft blocks (they won't damage stone, for example), but if it can destroy a build that's certainly a problem.

The aevitas thing makes sense, and I'll make sure to fix that.

**Comment by InterwovenWasTaken** [comment]
Thanks for the Aevitas change.

The mod maker confirmed that the Shooting Stars have an explosion power of 4.5, just over TNT (which has 4,) which matches with my observations.

Explosion power 4.5 is enough that, with a direct hit, it can destroy any block that a non-Wither explosion can destroy (so not Obsidian, Bedrock, Water, Lava) and can also do so through a layer of dirt (though it's not guaranteed to do so, since applied explosion power includes some randomization, and it can break more than that as well.)
