### ISSUE TITLE
Bug? Neromantic Prime annihilates blocks rather than mining them.

### ISSUE THREAD

**Issue by InterwovenWasTaken** [SoSly/minecraft#33]
When I used a Neromantic Prime to open a hole for fluid harvesting, it is supposedly meant to drop all the blocks it destroys into the world as items.

Currently, it does not do so. This has happened both times I have used it.

**Comment by nivthefox** [comment]
This sounds like a bug to report on the Astral Sorcery issues, rather than to me.  Genuine bugs within a mod are outside of my control.
