### ISSUE TITLE
Dark Roleplay Medieval 

### ISSUE THREAD

**Issue by darjeelingest** [SoSly/minecraft#38]
**Mod URL:** https://www.curseforge.com/minecraft/mc-mods/dark-roleplay-medieval

**Mod Description:** Cosmetic mod that adds new blocks and building options for a medieval flare

**Why you want it:** Its roofs are *very cool* and add a lot of building customization options that line up well thematically with the overall feel of things on the server

**Comment by nivthefox** [comment]
This also requires https://www.curseforge.com/minecraft/mc-mods/dark-roleplay-core.

**Comment by nivthefox** [comment]
This is on hold. We are considering using [Conquest Reforged](https://www.curseforge.com/minecraft/mc-mods/conquest-reforged), instead.
