### ISSUE TITLE
Configuration Request: Turn off Ghosts

### ISSUE THREAD

**Issue by InterwovenWasTaken** [SoSly/minecraft#41]
I would like to request that the Bewitchment mob Ghosts be prevented from being spawned.

This request is almost wholly selfish - my Pelotrio ritual can sometimes generate ghosts, since they're a standard overworld spawn, and unlike other mobs I cannot confine them to an arena only for the people fighting, since they both fly and pass through blocks.

To my knowledge, their one unique drop is Spectral Dust, which is used in one Bewitchment ritual (Ritual of the Spiritual Rift) and one Bewitchment brew (Glowing)

As an alternative recipe, perhaps Spectral Dust could be created by mixing Chalk Dust and Ectoplasm?

It's not terribly important, if that's difficult or someone likes them - they don't spawn often enough to be a problem.

**Comment by nivthefox** [comment]
Declined. I like them.
