### ISSUE TITLE
Botanic Additions

### ISSUE THREAD

**Issue by anomalagous** [SoSly/minecraft#42]
**Mod URL:**  https://www.curseforge.com/minecraft/mc-mods/botanic-additions

**Mod Description:** Extra bits and baubles for Botania.

**Why you want it:** If only for adding sparks to runic altars, by god, let me add sparks to runic altars.

**Comment by InterwovenWasTaken** [comment]
I like the generating flowers, the ways of moving mana, and the decorative aspect.
Can we disable Gaiasteel equipment (which the mod seems to imply it adds, though it might only add the material) and the more-powerful baubles?

**Comment by nivthefox** [comment]
On review I've decided not to include this one.  It's got very little configuration and control, which makes it hard to get rid of the things we definitely don't want.
