### ISSUE TITLE
Growthcraft

### ISSUE THREAD

**Issue by anomalagous** [SoSly/minecraft#43]
**Mod URL:** https://www.curseforge.com/minecraft/mc-mods/growthcraft-community-edition

**Mod Description:** Adds some fun brewing and cheesemaking mechanics.

**Why you want it:** I WISH TO BREWWWWW.

**Comment by nivthefox** [comment]
I think we're going to leave this out for now, because we've already got all of the things this adds. I know it makes it more exciting to brew or create cheese or the like, but I am concerned about too many fluffy filler mods that don't add unique content.  I'm sorry. :(
